export const UPDATA_GOODSLIST = "goods/UPDATA_GOODSLIST"
export const UPDATA_PAGE_SIZE = 'goods/UPDATA_PAGE_SIZE'
export const UPDATA_CURRENT_PAGE = 'goods/UPDATA_CURRENT_PAGE'
export const UPDATA_GOODS_CAREGORIES = 'goods/UPDATA_GOODS_CAREGORIES'
export const UPDATA_CATELIST = 'goods/UPDATA_CATELIST'
export const UPDATA_CATELIST_PAGESIZE = 'goods/UPDATA_CATELIST_PAGESIZE'
export const UPDATA_CATELIST_CURRENTPAGE = 'goods/UPDATA_CATELIST_CURRENTPAGE'